// taproot setup
// Interactive wizard that configures the system without editing files.
// Writes ~/.taproot/.env and zones.yaml.

import { createInterface } from 'node:readline';
import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

const BOLD = '\x1b[1m';
const DIM = '\x1b[2m';
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const RESET = '\x1b[0m';

const ENV_DIR = join(homedir(), '.taproot');
const ENV_PATH = join(ENV_DIR, '.env');

const rl = createInterface({ input: process.stdin, output: process.stdout });

function ask(question, defaultValue) {
  const prompt = defaultValue
    ? `${question} ${DIM}[${defaultValue}]${RESET}: `
    : `${question}: `;
  return new Promise(resolve => {
    rl.question(prompt, answer => {
      resolve(answer.trim() || defaultValue || '');
    });
  });
}

function confirm(question) {
  return new Promise(resolve => {
    rl.question(`${question} (y/n): `, answer => {
      resolve(answer.trim().toLowerCase() === 'y');
    });
  });
}

export async function runSetup() {
  console.log(`\n${BOLD}Taproot - Setup Wizard${RESET}\n`);

  if (existsSync(ENV_PATH)) {
    console.log(`${YELLOW}An existing configuration was found at ${ENV_PATH}${RESET}`);
    const proceed = await confirm('Overwrite it?');
    if (!proceed) {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  console.log(`This wizard will walk you through configuring the system.`);
  console.log(`You'll need your API keys ready. Press Enter to accept defaults.\n`);

  // --- Rachio ---
  console.log(`${BOLD}1. Rachio Controller${RESET}`);
  console.log(`${DIM}Find your API key at: https://rachio.com -> Account Settings -> Get API Key${RESET}`);
  const rachioKey = await ask('Rachio API key');
  if (!rachioKey) {
    console.log(`${YELLOW}Warning: Rachio API key is required for the system to work.${RESET}`);
  }

  // --- Ambient Weather ---
  console.log(`\n${BOLD}2. Ambient Weather Station${RESET} ${DIM}(optional but recommended)${RESET}`);
  console.log(`${DIM}Find your keys at: https://ambientweather.net -> My Account -> API Keys${RESET}`);
  const useAmbient = await confirm('Do you have an Ambient Weather station?');

  let ambientKey = '', ambientApp = '', ambientMac = '';
  if (useAmbient) {
    ambientKey = await ask('Ambient Weather API key');
    ambientApp = await ask('Ambient Weather Application key');
    ambientMac = await ask('Station MAC address');
  }

  // --- Notifications ---
  console.log(`\n${BOLD}3. Notifications${RESET}`);
  console.log(`${DIM}Notifications currently go through an optional webhook receiver such as n8n.${RESET}`);
  const webhookUrl = await ask('n8n webhook URL (or leave blank to skip)');
  const email = await ask('Notification email address (optional, for your webhook flow)');

  // --- Location ---
  console.log(`\n${BOLD}4. Location${RESET}`);
  console.log(`${DIM}Used for forecast queries and local scheduling. Default is Denver, CO.${RESET}`);
  const changeLoc = await confirm('Change location from Denver, CO?');
  let lat = '39.73220';
  let lon = '-105.21940';
  let timezone = 'America/Denver';
  if (changeLoc) {
    lat = await ask('Latitude', '39.73220');
    lon = await ask('Longitude', '-105.21940');
    timezone = await ask('Timezone', 'America/Denver');
  }

  // --- MQTT ---
  console.log(`\n${BOLD}5. Home Assistant Integration${RESET} ${DIM}(optional)${RESET}`);
  const useMqtt = await confirm('Connect to an MQTT broker for Home Assistant?');
  let mqttUrl = '';
  if (useMqtt) {
    mqttUrl = await ask('MQTT broker URL', 'mqtt://192.168.68.110:1883');
  }

  // --- Debug ---
  console.log(`\n${BOLD}6. Debug Level${RESET}`);
  const debugLevel = await ask('Debug level (0=errors, 1=info, 2=debug)', '1');

  // --- Write .env ---
  console.log(`\n${BOLD}Writing configuration...${RESET}`);

  if (!existsSync(ENV_DIR)) {
    mkdirSync(ENV_DIR, { recursive: true });
  }

  const envContent = [
    '# Taproot Configuration',
    `# Generated by setup wizard on ${new Date().toISOString()}`,
    '',
    '# Rachio',
    `RACHIO_API_KEY=${rachioKey}`,
    '',
    '# Ambient Weather',
    `AMBIENT_API_KEY=${ambientKey}`,
    `AMBIENT_APP_KEY=${ambientApp}`,
    `AMBIENT_MAC_ADDRESS=${ambientMac}`,
    '',
    '# Notifications',
    `NOTIFICATION_EMAIL=${email}`,
    webhookUrl ? `N8N_WEBHOOK_URL=${webhookUrl}` : '# N8N_WEBHOOK_URL=',
    '',
    '# MQTT',
    mqttUrl ? `MQTT_BROKER_URL=${mqttUrl}` : '# MQTT_BROKER_URL=',
    '',
    '# System',
    `DEBUG_LEVEL=${debugLevel}`,
    'SHADOW_MODE=true',
    '',
    '# Location',
    `LAT=${lat}`,
    `LON=${lon}`,
    `LOCATION_TIMEZONE=${timezone}`,
  ].join('\n') + '\n';

  writeFileSync(ENV_PATH, envContent, { mode: 0o600 });
  console.log(`${GREEN}OK${RESET}  Wrote ${ENV_PATH}`);

  // --- Summary ---
  console.log(`\n${BOLD}Setup complete!${RESET}\n`);
  console.log(`${YELLOW}Shadow mode is ON by default.${RESET} The system will log decisions`);
  console.log(`but will NOT send commands to your Rachio controller.\n`);
  console.log(`Next steps:`);
  console.log(`  1. Run ${BOLD}taproot doctor${RESET} to verify connectivity`);
  console.log(`  2. Run ${BOLD}taproot run --shadow${RESET} to test a decision cycle`);
  console.log(`  3. Edit ${BOLD}zones.yaml${RESET} if your zone layout differs from defaults`);
  console.log(`  4. After a week of shadow runs, run ${BOLD}taproot go-live${RESET}`);
  console.log('');

  rl.close();
}
