import yaml from 'js-yaml';
import { deleteEnvValue, readEnvValueFromContent, upsertEnvValue } from './env.js';

const ENV_HEADER = '# Smart Water System Configuration';
const ZONE_HEADER = `# Smart Water System - Zone Configuration
#
# Generated by the guided web editor.
# Use the advanced editor if you want to add comments or custom YAML formatting.
`;

function trimValue(value) {
  return String(value ?? '').trim();
}

function parseFloatOrFallback(value, fallback) {
  const parsed = parseFloat(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function parseIntOrFallback(value, fallback) {
  const parsed = parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function ensureEnvHeader(content) {
  const trimmed = content.trim();
  if (!trimmed) {
    return `${ENV_HEADER}\n`;
  }
  return content;
}

function setOptionalEnvValue(content, key, value, fallback = '') {
  const nextValue = trimValue(value);
  if (!nextValue || nextValue === fallback) {
    return deleteEnvValue(content, key);
  }
  return upsertEnvValue(content, key, nextValue);
}

function setRequiredEnvValue(content, key, value) {
  return upsertEnvValue(content, key, trimValue(value));
}

function fallbackZoneDocument(fallback = {}) {
  const soilProfiles = {};
  for (const [name, profile] of Object.entries(fallback.soilProfiles || {})) {
    soilProfiles[name] = {
      organic_matter_pct: profile.organicMatterPercent ?? 2.0,
      soil_ph: profile.soilPH ?? 7.5,
    };
  }

  const zones = {};
  for (const [zoneNumber, profile] of Object.entries(fallback.zoneProfiles || {})) {
    zones[zoneNumber] = {
      type: profile.type ?? 'lawn',
      sun_exposure: profile.sunExposure ?? 1.0,
      area_sqft: profile.areaSqFt ?? 400,
      priority: profile.priority ?? 2,
      soil: profile.soil ?? 'default',
    };
  }

  return { soil_profiles: soilProfiles, zones };
}

export function buildGuidedSettingsModel(envContent = '') {
  const get = key => readEnvValueFromContent(envContent, key);
  const has = key => Boolean(trimValue(get(key)));

  return {
    notificationEmail: get('NOTIFICATION_EMAIL') || '',
    webhookUrl: get('N8N_WEBHOOK_URL') || '',
    mqttBrokerUrl: get('MQTT_BROKER_URL') || '',
    mqttTopicPrefix: get('MQTT_TOPIC_PREFIX') || '',
    debugLevel: get('DEBUG_LEVEL') || '1',
    shadowMode: (get('SHADOW_MODE') || 'true') === 'true',
    lat: get('LAT') || '39.73220',
    lon: get('LON') || '-105.21940',
    locationTimezone: get('LOCATION_TIMEZONE') || 'America/Denver',
    webHost: get('WEB_HOST') || '',
    webPort: get('WEB_PORT') || '',
    rachioConfigured: has('RACHIO_API_KEY'),
    ambientApiConfigured: has('AMBIENT_API_KEY'),
    ambientAppConfigured: has('AMBIENT_APP_KEY'),
    ambientMacConfigured: has('AMBIENT_MAC_ADDRESS'),
    webUiPasswordConfigured: has('WEB_UI_PASSWORD'),
  };
}

export function applyGuidedSettings(envContent, values) {
  let content = ensureEnvHeader(envContent);

  const secretUpdates = [
    ['RACHIO_API_KEY', values.rachioApiKey],
    ['AMBIENT_API_KEY', values.ambientApiKey],
    ['AMBIENT_APP_KEY', values.ambientAppKey],
    ['AMBIENT_MAC_ADDRESS', values.ambientMacAddress],
  ];

  for (const [key, value] of secretUpdates) {
    if (trimValue(value)) {
      content = setRequiredEnvValue(content, key, value);
    }
  }

  content = setOptionalEnvValue(content, 'NOTIFICATION_EMAIL', values.notificationEmail);
  content = setOptionalEnvValue(content, 'N8N_WEBHOOK_URL', values.webhookUrl);
  content = setOptionalEnvValue(content, 'MQTT_BROKER_URL', values.mqttBrokerUrl);
  content = setOptionalEnvValue(content, 'MQTT_TOPIC_PREFIX', values.mqttTopicPrefix, 'smart-water');
  content = setOptionalEnvValue(content, 'WEB_HOST', values.webHost, '127.0.0.1');
  content = setOptionalEnvValue(content, 'WEB_PORT', values.webPort, '3000');

  content = setRequiredEnvValue(content, 'DEBUG_LEVEL', values.debugLevel || '1');
  content = setRequiredEnvValue(content, 'SHADOW_MODE', values.shadowMode ? 'true' : 'false');
  content = setRequiredEnvValue(content, 'LAT', values.lat || '39.73220');
  content = setRequiredEnvValue(content, 'LON', values.lon || '-105.21940');
  content = setRequiredEnvValue(content, 'LOCATION_TIMEZONE', values.locationTimezone || 'America/Denver');

  if (values.disableWebUiPassword) {
    content = deleteEnvValue(content, 'WEB_UI_PASSWORD');
  } else if (trimValue(values.webUiPassword)) {
    content = setRequiredEnvValue(content, 'WEB_UI_PASSWORD', values.webUiPassword);
  }

  return `${content.replace(/\s+$/, '')}\n`;
}

export function parseZoneConfig(rawYaml, fallback = {}) {
  let parsed = null;
  if (trimValue(rawYaml)) {
    parsed = yaml.load(rawYaml, { schema: yaml.JSON_SCHEMA });
  }

  const fallbackDoc = fallbackZoneDocument(fallback);
  const source = {
    soil_profiles: parsed?.soil_profiles && Object.keys(parsed.soil_profiles).length > 0
      ? parsed.soil_profiles
      : fallbackDoc.soil_profiles,
    zones: parsed?.zones && Object.keys(parsed.zones).length > 0
      ? parsed.zones
      : fallbackDoc.zones,
  };

  const soilProfiles = Object.entries(source.soil_profiles || {})
    .map(([name, profile]) => ({
      name,
      organicMatterPct: parseFloatOrFallback(profile?.organic_matter_pct, 2.0),
      soilPh: parseFloatOrFallback(profile?.soil_ph, 7.5),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

  const zones = Object.entries(source.zones || {})
    .map(([zoneNumber, zone]) => ({
      zoneNumber: parseIntOrFallback(zoneNumber, 0),
      type: zone?.type === 'drip' ? 'drip' : 'lawn',
      sunExposure: parseFloatOrFallback(zone?.sun_exposure, 1.0),
      areaSqFt: parseFloatOrFallback(zone?.area_sqft, 400),
      priority: parseIntOrFallback(zone?.priority, 2),
      soil: trimValue(zone?.soil) || 'default',
    }))
    .filter(zone => zone.zoneNumber > 0)
    .sort((a, b) => a.zoneNumber - b.zoneNumber);

  return { soilProfiles, zones };
}

export function normalizeSoilProfiles(rows) {
  const seen = new Set();
  const profiles = [];

  for (const row of rows) {
    const name = trimValue(row.name);
    if (!name) continue;

    if (!/^[A-Za-z0-9_-]+$/.test(name)) {
      throw new Error(`Soil profile "${name}" must use letters, numbers, dashes, or underscores`);
    }
    if (seen.has(name)) {
      throw new Error(`Soil profile "${name}" is duplicated`);
    }

    const organicMatterPct = parseFloat(row.organicMatterPct);
    const soilPh = parseFloat(row.soilPh);

    if (!Number.isFinite(organicMatterPct) || organicMatterPct < 0 || organicMatterPct > 25) {
      throw new Error(`Soil profile "${name}" must have organic matter between 0 and 25`);
    }
    if (!Number.isFinite(soilPh) || soilPh <= 0 || soilPh > 14) {
      throw new Error(`Soil profile "${name}" must have pH between 0 and 14`);
    }

    profiles.push({ name, organicMatterPct, soilPh });
    seen.add(name);
  }

  if (profiles.length === 0) {
    throw new Error('At least one soil profile is required');
  }

  return profiles.sort((a, b) => a.name.localeCompare(b.name));
}

export function normalizeZones(rows, soilProfileNames) {
  const seen = new Set();
  const validSoils = new Set(soilProfileNames);
  const zones = [];

  for (const row of rows) {
    const zoneNumber = parseInt(trimValue(row.zoneNumber), 10);
    if (!Number.isFinite(zoneNumber) || zoneNumber <= 0) continue;

    if (seen.has(zoneNumber)) {
      throw new Error(`Zone ${zoneNumber} is duplicated`);
    }

    const type = trimValue(row.type);
    const sunExposure = parseFloat(row.sunExposure);
    const areaSqFt = parseFloat(row.areaSqFt);
    const priority = parseInt(trimValue(row.priority), 10);
    const soil = trimValue(row.soil);

    if (!['lawn', 'drip'].includes(type)) {
      throw new Error(`Zone ${zoneNumber} must be lawn or drip`);
    }
    if (!Number.isFinite(sunExposure) || sunExposure < 0 || sunExposure > 1) {
      throw new Error(`Zone ${zoneNumber} sun exposure must be between 0.0 and 1.0`);
    }
    if (!Number.isFinite(areaSqFt) || areaSqFt <= 0) {
      throw new Error(`Zone ${zoneNumber} area must be greater than 0`);
    }
    if (!Number.isFinite(priority) || priority < 1 || priority > 9) {
      throw new Error(`Zone ${zoneNumber} priority must be between 1 and 9`);
    }
    if (!validSoils.has(soil)) {
      throw new Error(`Zone ${zoneNumber} references unknown soil profile "${soil}"`);
    }

    zones.push({ zoneNumber, type, sunExposure, areaSqFt, priority, soil });
    seen.add(zoneNumber);
  }

  if (zones.length === 0) {
    throw new Error('At least one zone is required');
  }

  return zones.sort((a, b) => a.zoneNumber - b.zoneNumber);
}

export function buildZoneConfigYaml({ soilProfiles, zones }) {
  const doc = {
    soil_profiles: {},
    zones: {},
  };

  for (const soil of soilProfiles) {
    doc.soil_profiles[soil.name] = {
      organic_matter_pct: soil.organicMatterPct,
      soil_ph: soil.soilPh,
    };
  }

  for (const zone of zones) {
    doc.zones[zone.zoneNumber] = {
      type: zone.type,
      sun_exposure: zone.sunExposure,
      area_sqft: zone.areaSqFt,
      priority: zone.priority,
      soil: zone.soil,
    };
  }

  return `${ZONE_HEADER}\n${yaml.dump(doc, { lineWidth: 100, sortKeys: false })}`;
}
